apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: vsheffer/kubernetes-debug-shell
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
